# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: deploying the application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secret.HOST }}
        user: ${{ secrets.USER }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY  }}
        
        script: |
          apt install apache2 curl -y
          curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
          source ~/.bashrc   
          nvm install node 14
          npm install pm2 -g
          cd /var/www/html
          git pull origin main
          pm2 start "node app.js"
          
          
          
